// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMULT_H
#define XMULT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmult_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMult_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMult;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMult_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMult_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMult_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMult_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMult_Initialize(XMult *InstancePtr, u16 DeviceId);
XMult_Config* XMult_LookupConfig(u16 DeviceId);
int XMult_CfgInitialize(XMult *InstancePtr, XMult_Config *ConfigPtr);
#else
int XMult_Initialize(XMult *InstancePtr, const char* InstanceName);
int XMult_Release(XMult *InstancePtr);
#endif

void XMult_Start(XMult *InstancePtr);
u32 XMult_IsDone(XMult *InstancePtr);
u32 XMult_IsIdle(XMult *InstancePtr);
u32 XMult_IsReady(XMult *InstancePtr);
void XMult_EnableAutoRestart(XMult *InstancePtr);
void XMult_DisableAutoRestart(XMult *InstancePtr);
u32 XMult_Get_return(XMult *InstancePtr);


void XMult_InterruptGlobalEnable(XMult *InstancePtr);
void XMult_InterruptGlobalDisable(XMult *InstancePtr);
void XMult_InterruptEnable(XMult *InstancePtr, u32 Mask);
void XMult_InterruptDisable(XMult *InstancePtr, u32 Mask);
void XMult_InterruptClear(XMult *InstancePtr, u32 Mask);
u32 XMult_InterruptGetEnabled(XMult *InstancePtr);
u32 XMult_InterruptGetStatus(XMult *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
